name: Build and Publish YCInfraBot
on:
  push:
    branches:
      - master
      - dev
    paths:
      - '*'
      - '!README.md'

jobs:
  deploy:
    name: Build and deploy yukkuricraft.net
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@master
      with:
        token: ${{secrets.YCINFRABOT_PAT_REMI}}
        submodules: recursive

    - name: Get short SHA
      id: short_sha
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.GCP_SA_JSON_KEY }}
        registry: gcr.io
        repository: ${{ secrets.GCR_REPOSITORY }}
        tags: latest
        build_args: COMMIT_SHA8=${{steps.short_sha.outputs.sha8}}
